[package]
name = "packem-logger"
version = "0.1.0"
authors = ["Saddam M <alimohamuda80@gmail.com>"]
edition = "2018"

[dependencies]
log = { version = "^0.4.5", features = ["std"] }
colored = "1.8.0"
